# action.yml
name: 'Print customizable alpine version'
description: 'print alpine version'
inputs:
  alpine-version:
    description: 'alpine version'
    required: false
    default: '3.9.5'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alpine-version }}