# action.yml
name: 'Print customizable alpine version'
description: 'print alpine version'
inputs:
  alpine-version:
    description: 'alpine version'
    required: true
outputs:
  alpine-version-running:
    description: 'alpine version that is running now'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.alpine-version }}