# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  dockerfile: #TODO despues borrar
    description: 'specify Dockerfile to use'
    required: false
    default: 'Dockerfile'
  docker-build-args: #TODO despues borrar
    description: 'docker build-args arguments'
    required: false
    default: '--build-arg alpine_version=3.9.5'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f ${{ inputs.dockerfile }}
    - ${{ inputs.docker-build-args }}