on: [push]

jobs:
  parameterizable_docker_action_test_job:
    runs-on: ubuntu-latest
    name: A job to create parameterizable docker action
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout to root dir
      uses: actions/checkout@v2
    - name: Hello world action step #TODO cambiar esto
      id: hello #TODO cambiar esto
      uses: ./
      with:
        alpine-version: '3.9.5'
    # Use the output from the `hello` step #TODO cambiar esto
    - name: Get alpine version
      run: echo "Alpine version is ${{ steps.hello.outputs.alpine-version-running }}"
